version: '3.4'

services:
  capybarapetapp.api:
    image: ${DOCKER_REGISTRY-}capybarapetappapi
    build:
      context: .
      dockerfile: CapybaraPetApp.Api/Dockerfile
    depends_on:
      - capybarapetapp-db

  capybarapetapp-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: CapybaraPetApp.Db
    environment:
       ACCEPT_EULA: Y
       MSSQL_SA_PASSWORD: Admin123.
       MSSQL_PID: Developer
       MSSQL_TCP_PORT: 1234 
    volumes:
       - ./.containers/database:/var/opt/mssql/data
    ports:
       - "1234:1234"