volumes:
  sql-data:
  identity-data:

services:
  api:
    image: capybarapetapp/api
    container_name: CapybaraPetApp.Api
    build:
      context: .
      dockerfile: CapybaraPetApp.Api/Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:8080"
    depends_on: [ database ]
    restart: on-failure

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: CapybaraPetApp.Db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin123.
    volumes:
      - sql-data:/var/opt/mssql
    ports:
      - "1433:1433"
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - identity-data:/opt/keycloak/data
    ports:
      - "18080:8080"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"