// <auto-generated />
using System;
using CapybaraPetApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CapybaraPetApp.Infrastructure.Migrations
{
    [DbContext(typeof(CapybaraPetAppDbContext))]
    [Migration("20251028163502_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapybaraPetApp.Domain.AchievementAggregate.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Achievement", (string)null);
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.CapybaraAggregate.Capybara", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Capybara", (string)null);
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.Common.JoinTables.AdoptionHistory", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapybaraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AdoptionDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "CapybaraId");

                    b.HasIndex("CapybaraId");

                    b.ToTable("User_Capybara", (string)null);
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.Common.JoinTables.Interaction.InteractionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapybaraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("InteractedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id", "UserId", "CapybaraId");

                    b.HasIndex("CapybaraId");

                    b.HasIndex("UserId");

                    b.ToTable("InteractionHistory", (string)null);
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.Common.JoinTables.UserAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UnlockedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("User_Achievement", (string)null);
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.Common.JoinTables.UserItem", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("User_Item", (string)null);
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.ItemAggregate.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.CapybaraAggregate.Capybara", b =>
                {
                    b.OwnsOne("CapybaraPetApp.Domain.CapybaraAggregate.CapybaraStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("CapybaraId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Energy")
                                .HasColumnType("int");

                            b1.Property<int>("Happiness")
                                .HasColumnType("int");

                            b1.Property<int>("Health")
                                .HasColumnType("int");

                            b1.HasKey("CapybaraId");

                            b1.ToTable("Capybara");

                            b1.WithOwner()
                                .HasForeignKey("CapybaraId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.Common.JoinTables.AdoptionHistory", b =>
                {
                    b.HasOne("CapybaraPetApp.Domain.CapybaraAggregate.Capybara", "Capybara")
                        .WithMany()
                        .HasForeignKey("CapybaraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapybaraPetApp.Domain.UserAggregate.User", "User")
                        .WithMany("UserCapybaras")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capybara");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.Common.JoinTables.Interaction.InteractionHistory", b =>
                {
                    b.HasOne("CapybaraPetApp.Domain.CapybaraAggregate.Capybara", null)
                        .WithMany()
                        .HasForeignKey("CapybaraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapybaraPetApp.Domain.UserAggregate.User", null)
                        .WithMany("Interactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.Common.JoinTables.UserAchievement", b =>
                {
                    b.HasOne("CapybaraPetApp.Domain.AchievementAggregate.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapybaraPetApp.Domain.UserAggregate.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.Common.JoinTables.UserItem", b =>
                {
                    b.HasOne("CapybaraPetApp.Domain.ItemAggregate.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapybaraPetApp.Domain.UserAggregate.User", "User")
                        .WithMany("UserItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.ItemAggregate.Item", b =>
                {
                    b.OwnsOne("CapybaraPetApp.Domain.ItemAggregate.ItemDetail", "ItemDetail", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("BonusEffect")
                                .HasColumnType("int");

                            b1.Property<string>("ItemType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ItemId");

                            b1.ToTable("Item");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("ItemDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("CapybaraPetApp.Domain.UserAggregate.User", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserCapybaras");

                    b.Navigation("UserItems");
                });
#pragma warning restore 612, 618
        }
    }
}
