name: "IaC Deploy"

on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'
          
      - name: Terraform init
        run: terraform init
        working-directory: ./iac/
        
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./iac/
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./iac/
        
      - name: Terraform Apply
        run: terraform apply -var="sql_pass=${{ secrets.TF_VAR_DB_PASSWORD }}" -auto-approve tfplan
        working-directory: ./iac/
        
      - name: Notify failure
        if: failure()
        run: echo "Terraform apply failed for ${{ github.ref_name }}"