name: "IaC Deploy"

on:
  push:
    paths:
      - "iac/**"
    branches:
      - main

jobs: 
  terraform-deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'
          
      - name: Terraform init
        run: terraform init
        working-directory: ./iac/
        
      - name: Terraform plan
        run: terraform plan --output plan
        
        